src/Entity/Property.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @ORM\Entity
 * @Vich\Uploadable
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz',
        2 => 'Bois'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 5,
     *      max = 255,
     *      minMessage = "{{ limit }} charactères minimum",
     *      maxMessage = "{{ limit }} charactères maximum"
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *    min = 10,
     *    max = 400,
     *    notInRangeMessage = "Vous devez entrer un nombre entre {{ min }}m² et {{ max }}m² ",
     * )
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $address;

    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string")
     * @Assert\Regex("/^(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}$/")

     */
    private $postal_code;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @var File|null
     * @Assert\Image(
     *      mimeTypes="image/jpeg"
     * )
     * @Vich\UploadableField(mapping="property_images", fileNameProperty="imageName")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * 
     * @var \DateTimeInterface
     */
    private $updatedAt;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $postalCodeWithoutSpace = str_replace(' ', '', $postal_code);
        $this->postal_code = $postalCodeWithoutSpace;

        return $this;
    }

    /**
     * @return Collection<int, Option>
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        $this->options->removeElement($option);

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;

        if ($imageFile) {
            $this->updatedAt = new \DateTime('now');
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use PhpParser\Parser\Multiple;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getHeatChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true,
                'required' => false,
                'attr' => ['class' => 'select2options']

            ])
            ->add('city')
            ->add('address')
            ->add('sold')
            ->add('postal_code')
            ->add('imageFile', FileType::class, [
                'required' => false,
                'label' => 'Image à la une',
                'attr' => [
                    'class' => 'form-control'
                ]
            ]);
    }

    private function getHeatChoices(): array
    {
        $heatArray = Property::HEAT;
        $heatArrayFlip = array_flip($heatArray);

        return $heatArrayFlip;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertyFilterSearch;
use App\Form\ContactType;
use App\Form\PropertyFilterSearchType;
use App\Notifications\ContactNotification;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    private $repository;

    public function __construct(PropertyRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/biens", name="app_property")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new PropertyFilterSearch;
        $form = $this->createForm(PropertyFilterSearchType::class, $search);
        $form->handleRequest($request);
        $datas = $this->repository->findBySearch($search);
        if (empty($datas)) {
            $this->addFlash('error', 'Aucun bien trouvé');
        }
        $properties = $paginator->paginate(
            $datas,
            $request->query->getInt('page', 1),
            8
        );
        $properties->setCustomParameters([
            'align' => 'center'
        ]);

        return $this->render('property/index.html.twig', [
            'controller_name' => 'PropertyController',
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @return Response
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification): Response
    {

        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }
        //$property = $this->repository->findOneBy(['id' => $property->getId()]);

        $contact = new Contact;
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $notification->notify($contact);
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }

        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties',
            'form' => $form->createView()
        ]);
    }
}

templates/property/_propertyCards.html.twig
<div class="col-3">
	<div class="card mt-4">
		{% if property.imagename %}
			<img class="card-img-top" src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('my_thumb') }}" alt="Card image top">
		{% else %}
			<img class="card-img-top" src="{{ asset('images/maison_pd.jpg') | imagine_filter('my_thumb') }} " alt="Card image top">
		{% endif %}
		<div class="card-body">
			<h6 class="card-title text-primary">
				<a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.title }}</a>
			</h6>
			<h6>Ville:
				{{property.city}}
				({{property.postalCode}})</h6>
			<p class="card-text">{{ property.description|u.truncate(80, '...', false) }}</p>
			<h5 class='text-primary'>Prix:
				{{property.formattedPrice}}
				€</h5>
		</div>
	</div>
</div>

templates/property/_searchForm.html.twig
<div class="p-2 mb-4 bg-light rounded-3">
	<div class="container-fluid py-5">
		{{ form_start(form) }}
		<div class="row align-items-end">
			<div class="col-lg-3">
				{{ form_row(form.minValue)}}
			</div>
			<div class="col-lg-3">
				{{ form_row(form.maxValue)}}
			</div>
			<div class="col-lg-3">
				{{ form_row(form.minSurface)}}
			</div>
			<div class="col-lg-3">
				{{ form_row(form.maxSurface)}}
			</div>
			<div class="col-lg-3">
				{{ form_row(form.heat)}}
			</div>
			<div class="col-lg-3">
				{{ form_row(form.rooms)}}
			</div>
			<div class="col-lg-3">
				{{ form_row(form.bedrooms)}}
			</div>
			<div class="col-lg-3">
				{{ form_row(form.city)}}
			</div>
			<div class="col-lg-3">
				{{ form_row(form.options)}}
			</div>
			<div class="col-lg-3">
				<button class="btn btn-primary">Rechercher</button>
			</div>
		</div>
		{{ form_end(form) }}
	</div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos biens
{% endblock %}

{% block body %}
	<div class="container">
		<div class="p-5 mb-4 bg-light rounded-3 text-center">
			<div class="container-fluid py-5">
				<h1 class="display-5 fw-bold">Agence Seb Immo</h1>
				<p class="fs-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, repellat aut cumque quas provident eveniet iste quisquam illum similique id voluptates dolorem officiis labore alias quia quasi aliquid ipsa? Cupiditate.</p>
				<button class="btn btn-primary btn-lg" type="button">Example button</button>
			</div>
		</div>
		{% include "property/_searchForm.html.twig" %}
		<div class="row flex">
			{% for message in app.flashes('error') %}
				<div class="alert alert-danger">
					{{ message }}
				</div>
			{% endfor %}
			{% for property in properties %}
				{% include "property/_propertyCards.html.twig" %}
			{% endfor %}
		</div>
		<div class="mt-4">
			{{ knp_pagination_render(properties) }}
		</div>
	</div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{property.title}}
{% endblock %}

{% block body %}
	<div class="container">
		{% if not form.vars.valid %}
			<div class="alert alert-danger">
				Veullez remplir le formulaire correctement svp
			</div>
		{% endif %}
		{% for message in app.flashes('success') %}
			<div class="alert alert-success" role="alert">
				{{ message }}
			</div>
		{% endfor %}
		{% for message in app.flashes('error') %}
			<div class="alert alert-danger" role="alert">
				{{ message }}
			</div>
		{% endfor %}
		<div class="p-5 mb-4 bg-light rounded-3 text-center">
			<div class="row">
				<div class="col-md-8">
					{% if property.imagename %}
						<img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="main iamge">
					{% else %}
						<img src="{{ asset('images/maison_pd.jpg') | imagine_filter('medium') }} " alt="main image">
					{% endif %}
				</div>
				<div class="col-md-4">
					<h1>{{ property.title }}</h1>
					<h2>{{ property.rooms }}
						pièces -
						{{ property.surface}}
						m²</h2>
					<div class="text-primary" style="font-size: 4rem; font-weight: bold;">{{ property.formattedPrice }}
						€</div>
					<a href="#" class="btn btn-primary" id="contactButton" {% if form.vars.submitted %} style="display: none;" {% endif %}>Contacter l'agence</a>
					<div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;" {% endif %}>
						{{ form_start(form) }}
						<div class="row">
							<div class="col">{{form_row(form.firstName)}}</div>
							<div class="col">{{form_row(form.lastName)}}</div>
						</div>
						<div class="row">
							<div class="col">{{form_row(form.phoneNumber)}}</div>
							<div class="col">{{form_row(form.email)}}</div>
						</div>
						{{ form_rest(form)}}
						<div class="form-group">
							<button class="btn btn-primary">Envoyer</button>
							<div class="btn btn-danger" id="cancelButton">Annuler</div>
						</div>
						{{ form_end(form)}}
					</div>
				</div>
			</div>
		</div>

		<p>{{ property.description | nl2br }}

			<div class="row">
				<div class="col-md-8">
					<h2>Caractéristiques</h2>
					<table class="table table-striped">
						<tbody>
							<tr>
								<td>Surface habitable</td>
								<td>{{ property.surface }}
									m²</td>
							</tr>
							<tr>
								<td>Pièces</td>
								<td>{{ property.rooms }}</td>
							</tr>
							<tr>
								<td>Chambres</td>
								<td>{{ property.bedrooms }}</td>
							</tr>
							<tr>
								<td>Pièces</td>
								<td>{{ property.rooms }}</td>
							</tr>
							<tr>
								<td>Chauffage</td>
								<td>{{ property.heatType }}</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="col-md-4">
					<h2>Spécificités</h2>
					<ul class="list-group">
						{% for option in property.options %}
							<li class="list-group-item">{{option.name}}</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</p>
	</div>
{% endblock %}